### ISSUE TITLE
Question: Wondering whether you can achieve chaining by using the proxysocket.create() method

### ISSUE THREAD

**Issue by samuel-allan** [krisives/proxysocket#7]
I was wondering if it were possible to do the following:

```
var proxysocket = require('proxysocket');
var socket1 = proxysocket.create('socks1addr', 9050);
var socket2 = proxysocket.create('socks2addr', 9050, socket1);
var socket3 = proxysocket.create('socks3addr', 9050, socket2);
```

Would this achieve the desired effect? (in other words would it allow me to send a request in the following chain: Socks1 -> Socks2 -> Socks3 -> Internet), Thanks a lot :D

**Comment by huumanoid** [comment]
Thank you for an interesting case.

I've just tested it.
Yes, it probably would.
But now you can't use this library for this purposes.
Because proxysocket's interface have some inconsistencies with nodejs socket interface.

The prototype of proxysocket's `connect` method looks like this:
```js
function connect(connectHost, connectPort, cb) {
```

While nodejs socket has the following `connect`:
```js
function connect(connectPort, connectHost, cb) {
```

If you swap `connectionHost` and `connectionPort` in `connect` here https://github.com/krisives/proxysocket/blob/master/proxysocket.js#L326
you may achieve the desired effect, I guess.

**Comment by huumanoid** [comment]
Please, test the fix proposed above:
https://github.com/huumanoid/proxysocket/tree/feature-chaining

`npm install github:huumanoid/proxysocket#feature-chaining`

Please, note, this change breaks backward compatibility.

Now, to connect, you have to do following:
```js
socket3.connect(PORT, HOST, cb)
```

**Comment by samuel-allan** [comment]
Oh, nice work! The repository is a great idea overall, as it provides a lot more useful functions than more popular harder-to-customize libraries. Thanks a lot for the help :D

**Comment by krisives** [comment]
I was not aware we no longer match the prototype we should fix that

**Comment by krisives** [comment]
Did my mean to close sorry on mobile

**Comment by krisives** [comment]
I merged the socket chaining and our goal now is to match the same signature/prototype of NodeJS socket.connect(). I don't know when this changed or if I wrote it wrong originally but the goal is to provide an identical interface so applications don't have to code around proxysocket itself.
